[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 5173

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Proxy for Roblox API through Netlify function
[[redirects]]
  from = "/api/roblox-proxy/*"
  to = "/.netlify/functions/roblox-proxy/:splat"
  status = 200
  force = true
